// Programs parsed from catalog.roosevelt.edu undergraduate + graduate A-Z (main content links).
// Regenerate with scripts if the catalog structure changes.
window.ROOSEVELT_PROGRAMS = [
  "Accounting Forensics, MSAF",
  "Accounting, BSBA",
  "Accounting, Minor (for Business Majors)",
  "Accounting, Minor (for Non-Business Majors)",
  "Accounting, MSA",
  "Acting, BFA",
  "Actuarial Science, BA",
  "Actuarial Science, BA/MS Computer Science Accelerated Program",
  "Actuarial Science, BS",
  "Actuarial Science, BS/MS Computer Science Accelerated Program",
  "Actuarial Science, BS/MS Mathematics",
  "Actuarial Sciences, BS/MS Accelerated Program",
  "Actuarial Sciences, MS",
  "African American Studies, Minor",
  "Arts, Entertainment, and Media Business, BA",
  "Bilingual/ESL Education, Certificate",
  "Bilingual/ESL Education, Minor",
  "Biochemistry, BS",
  "Biology BS, Pharmacy PharmD Dual Degree Acceptance Program",
  "Biology, BA",
  "Biology, BA to Secondary Education, MA Accelerated Program",
  "Biology, BS",
  "Biology, BS/BA to Biology, MS Accelerated Program",
  "Biology, Minor",
  "Biology, MS",
  "Biomedical Sciences, MA",
  "Biotechnology and Chemical Science, MS",
  "Business Administration, MBA",
  "Business Administration, MBA, Dual Degree with Industrial/Organizational Psychology, MA",
  "Business Analytics, Certificate",
  "Business Analytics, MS",
  "Chemistry, Minor",
  "Child and Family Studies Concentration",
  "Classical Performance (Strings and Harp), BM",
  "Classical Performance (Strings), Performance Diploma (PED)",
  "Classical Performance - Guitar, BM",
  "Classical Performance - Guitar, MM",
  "Classical Performance - Guitar, Performance Diploma (PED)",
  "Classical Performance - Multiples Woodwinds, MM",
  "Classical Performance - Piano, BM",
  "Classical Performance - Piano, MM",
  "Classical Performance - Piano, Performance Diploma (PED)",
  "Classical Performance - Voice, BM",
  "Classical Performance - Voice, MM",
  "Clinical Child and Family Psychology, Graduate Concentration",
  "Clinical Mental Health Counseling, MA",
  "Clinical Neuropsychology, Concentration",
  "Clinical Psychology (Counseling Practice), MA",
  "Clinical Psychology, Doctor of Psychology (PsyD)",
  "Collaborative Piano, MM",
  "Computer Science Bridge Program",
  "Computer Science BS/MS in Cyber Security Accelerated Program",
  "Computer Science, BS",
  "Computer Science, BS/MS Accelerated Program",
  "Computer Science, BS/MS Actuarial Science Accelerated Program",
  "Computer Science, BS/MS Mathematics Accelerated Program",
  "Computer Science, Certificate",
  "Computer Science, Minor",
  "Computer Science, MS",
  "Conflict and Mediation, MACM",
  "Conflict Resolution and Negotiation, Certificate",
  "Creative Writing, MFA",
  "Criminal Justice, BA",
  "Criminal Justice, BA/MA Conflict Mediation",
  "Criminal Justice, BA/MPA Public Administration",
  "Criminal Justice, Minor",
  "Cyber and Information Security, BS",
  "Cyber Security Bridge Program",
  "Cyber Security BS/MS Computer Science Accelerated Program",
  "Cyber Security Information Assurance, BS/MS Accelerated Program",
  "Cyber Security Information Assurance, Certificate",
  "Cyber Security Information Assurance, MS",
  "Data Analytics, Certificate",
  "Data Science, BS",
  "Data Science, BS/MS Actuarial Science Accelerated Program",
  "Data Science, BS/MS Computer Science Accelerated Program",
  "Data Science, BS/MS Mathematics Accelerated Program",
  "Data Science, Minor",
  "Data Science, MS",
  "Diagnostic Medical Sonography, BS",
  "Digital and Multimedia Communications, BA",
  "Digital Marketing, Advertising and Public Relations, BA to Marketing Communications, MSIMC",
  "Digital Marketing, Advertising and Public Relations, Minor",
  "Digital Marketing, Advertising, and Public Relations, BA",
  "Dual Language Principal Leadership, Certificate",
  "Dual Language Teacher Leadership, MA",
  "Early Childhood Education, BAE",
  "Early Childhood Education, MA",
  "Economics, BA",
  "Economics, Minor",
  "Education and Youth Studies, BAE",
  "Educational Studies, Minor",
  "Elementary Education, BAE",
  "Elementary Education, MA",
  "English Composition",
  "English, BA",
  "English, BA to Secondary Education, MA Accelerated Program",
  "English, Minor",
  "Environmental Science, Minor",
  "Exercise Nutrition Health Sciences, BA",
  "Film Studies, Minor",
  "Finance, BSBA",
  "Finance, Minor (for Business majors)",
  "Finance, Minor (for Non-Business Majors)",
  "Financial Risk Management, MS",
  "Fine Art, Minor",
  "Forensic Psychology Concentration",
  "General Business, Minor (for Non-Business Majors)",
  "General Psychology, MA",
  "Graphic Design, BA",
  "Graphic Design, Minor",
  "Health Science Administration, BA/MPA Public Administration",
  "Health Sciences, BA",
  "Health Services Management, Certificate",
  "Healthcare Ethics, Analytics and Law (Counter Fraud Studies), [HEAL] Graduate Certificate",
  "Hispanic Studies, Minor",
  "History BA/MA Accelerated Program",
  "History, BA",
  "History, BA to Secondary Education, MA Accelerated Program",
  "History, MA",
  "History, Minor",
  "Histotechnology, BS",
  "Hospitality and Tourism Management, BSHTM",
  "Hospitality and Tourism Management, Minor",
  "Hospitality and Tourism Management, MSHTM",
  "Human Resource Management, BSBA",
  "Human Resource Management, Certificate",
  "Human Resource Management, Minor (for Business majors)",
  "Human Resource Management, Minor (for Non-Business Majors)",
  "Human Resource Management, MSHRM",
  "Industrial/Organizational Psychology, MA",
  "Industrial/Organizational Psychology, MA, Dual Degree with MBA",
  "Information Systems Security, Certificate",
  "Information Technology, BA",
  "Information Technology, BA/MBA Accelerated Program",
  "Information Technology, BA/MS Computer Science Accelerated Program",
  "Information Technology, BA/MS Cyber Security and Information Assurance Accelerated Program",
  "Information Technology, Minor",
  "Instructional Leadership, MA",
  "Interdisciplinary Leadership Doctoral (Ed.D.) Program",
  "Interdisciplinary Studies, BA",
  "Interdisciplinary Theatre Studies, BA",
  "International Business, Minor",
  "International Studies, BA",
  "International Studies, Minor",
  "Journalism and Media Studies, BA",
  "Journalism, Minor",
  "Legal Studies, Minor",
  "Literacy Leadership, MA",
  "Management, BSBA",
  "Management, Minor (for Business majors)",
  "Management, Minor (for Non-Business Majors)",
  "Marketing Communications, MSIMC",
  "Marketing, BSBA",
  "Marketing, Minor (for Business majors)",
  "Marketing, Minor (for non-Business Majors)",
  "Master's in Pharmaceutical Sciences",
  "Masters Concentrations",
  "Mathematics, BA",
  "Mathematics, BA to Secondary Education, MA Accelerated Program",
  "Mathematics, BA/MS Computer Science Accelerated Program",
  "Mathematics, BS",
  "Mathematics, BS/MS Computer Science Accelerated Program",
  "Mathematics, Minor",
  "Mathematics, MS",
  "Media Studies, Minor",
  "Medical Technology, BS",
  "Mental Health Concentration",
  "Middle School Education, BAE",
  "Middle School Education, MA",
  "Music and Computing, BA",
  "Music Composition, BM",
  "Music Composition, Minor",
  "Music Composition, MM",
  "Music Education and Jazz Performance, BM",
  "Music Education, Instrumental Emphasis and Classical Performance, BM",
  "Music Education, Songwriting and Production Emphasis, BM",
  "Music, BA",
  "Music, Honors Interdisciplinary, BMA",
  "Music, Interdisciplinary Music Industry, BMA",
  "Musical Theatre - Dance, BFA",
  "Musical Theatre, BFA",
  "Neuroscience Concentration",
  "Nonprofit Management, Certificate",
  "Nuclear Medicine Technology, BS",
  "Nursing, BSN",
  "Opera, Professional Diploma (PD)",
  "Orchestral Studies (Brass, Percussion, and Winds), Professional Diploma (PD)",
  "Orchestral Studies (Strings), MM",
  "Orchestral Studies (Strings), Professional Diploma (PD)",
  "Organization Development, MAOD",
  "Organizational Leadership, BAOL",
  "Organizational Leadership, BAOL/MACM Conflict Mediation Accelerated Program",
  "Organizational Leadership, BAOL/MAOD Organization Development Accelerated Program",
  "Organizational Leadership, BAOL/MATD Training and Development Accelerated Program",
  "Organizational Leadership, BAOL/Public Administration, MPA",
  "Organizational Leadership, Minor (for Business Majors)",
  "Organizational Leadership, Minor (for Non-Business Majors)",
  "Paralegal Studies Minor",
  "Paralegal Studies, BA",
  "Paralegal Studies, Post-Baccalaureate Certificate",
  "Performing Arts Administration, MA",
  "Performing Arts Wellness Concentration",
  "Pharmacy Business Management Certificate",
  "Pharmacy, PharmD",
  "Pharmacy, PharmD/MBA Dual Degree Program",
  "Pharmacy, PharmD/MSPS Dual Degree Program",
  "Philosophy, BA",
  "Philosophy, Minor",
  "Political Philosophy Concentration",
  "Political Science, BA",
  "Political Science, BA/MPA Public Administration",
  "Political Science, Minor",
  "Pre-Health Professional Curricula",
  "Preclinical Psychology Post-Baccalaureate Certificate",
  "Psychology, BA",
  "Psychology, BA to Clinical Psychology (Counseling Practice), MA Accelerated Program",
  "Psychology, Minor",
  "Public Administration, MPA",
  "Public Finance, Certificate",
  "Public Sector Management, Certificate",
  "Radiation Therapy Technology, BS",
  "Radiography, BS",
  "Real Estate Development, Certificate",
  "Real Estate Finance Investment, Certificate",
  "Real Estate, BSBA",
  "Real Estate, Minor (for Business Majors)",
  "Real Estate, Minor (for Non-Business Majors)",
  "Real Estate, MSRE",
  "School Counseling, MA",
  "Second Language Special Education, MA",
  "Secondary Education, MA",
  "Secondary Teacher Education, Minor",
  "Social Emotional Learning and School Climate Certificate",
  "Social Emotional Learning and School Climate, Certificate",
  "Social Entrepreneurship, BSBA",
  "Social Entrepreneurship, Minor (for Business Majors)",
  "Social Entrepreneurship, Minor (for Non-Business Majors)",
  "Social Justice Studies, BA",
  "Social Justice Studies, Minor",
  "Sociology, BA",
  "Sociology, Minor",
  "Spanish for Health Care Professionals, Certificate",
  "Special Education, BAE",
  "Special Education, LBS1 Endorsement, Certificate",
  "Special Education, MA",
  "Statistics, Minor",
  "Sustainability Studies, BA",
  "Sustainability Studies, BA/MPA Public Administration",
  "Sustainability Studies, Minor",
  "Suzuki Pedagogy, Professional Diploma (PD)",
  "Training and Development, Certificate",
  "Training and Development, MATD",
  "Women's and Gender Studies, BA",
  "Women's and Gender Studies, Minor",
  "Woodwind, Brass, and Percussion Instruments, BM",
  "Writing, Minor"
];
